name: C

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libedit-dev
      run: sudo apt-get install -y libedit-dev valgrind time
    - name: Run tests
      run: make check
    - name: Run Valgrind (on tests)
      run: make memcheck
    - name: Run fib35 benchmark
      run: |
        echo "Time: "
        make
        /usr/bin/time bin/monkey examples/fib35.monkey | tail -n1
