name: C

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libedit-dev
      run: sudo apt-get install -y libedit-dev
    - name: make check
      run: make check